vich_uploader:
    db_driver: orm

    mappings:
        product:
            uri_prefix: /uploads/product
            upload_destination: "%kernel.project_dir%/public/uploads/product"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_profile:
            uri_prefix: /uploads/user_profile
            upload_destination: "%kernel.project_dir%/public/uploads/user_profile"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
